use std::path::Path;

use thiserror::Error;

use super::SUPPORTED_SCHEMA_VERSION;

const GENERATED_PREAMBLE_MARKER: &str = "# RACK:GENERATED";
const SCHEMA_HEADER_PREFIX: &str = "# RACK:V";

#[derive(Debug, Error)]
pub(crate) enum PreambleError {
    #[error("missing config schema header (expected `# RACK:V<version>`)")]
    MissingSchemaHeader,

    #[error("invalid config schema version in header `{0}`")]
    InvalidSchemaVersion(String),

    #[error("unsupported config schema version `{0}`")]
    UnsupportedSchemaVersion(u8),
}

pub(crate) fn parse_schema_version(input: &str) -> Result<u8, PreambleError> {
    let Some(header) = schema_header_line(input) else {
        return Err(PreambleError::MissingSchemaHeader);
    };

    let Some(version) = header.strip_prefix(SCHEMA_HEADER_PREFIX) else {
        return Err(PreambleError::MissingSchemaHeader);
    };

    let version = version
        .trim()
        .parse()
        .map_err(|_| PreambleError::InvalidSchemaVersion(version.trim().to_owned()))?;

    if version != SUPPORTED_SCHEMA_VERSION {
        return Err(PreambleError::UnsupportedSchemaVersion(version));
    }

    Ok(version)
}

pub(crate) fn format_schema_header(schema_version: u8) -> String {
    format!("{SCHEMA_HEADER_PREFIX}{schema_version}")
}

pub(crate) fn format_generated_preamble(source_path: &Path, schema_version: u8) -> String {
    format!(
        "{GENERATED_PREAMBLE_MARKER}\n# Source config is {}\n# Do not edit this file directly.\n\n{}",
        source_path.display(),
        format_schema_header(schema_version)
    )
}

fn schema_header_line(input: &str) -> Option<&str> {
    let mut lines = input.lines().map(str::trim).filter(|line| !line.is_empty());
    let first = lines.next()?;

    if first == GENERATED_PREAMBLE_MARKER {
        return lines.find(|line| line.starts_with(SCHEMA_HEADER_PREFIX));
    }

    Some(first)
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;

    #[test]
    fn parses_schema_version() {
        assert_eq!(
            parse_schema_version("# RACK:V1\nterminal = \"Ghostty\"").unwrap(),
            1
        );
    }

    #[test]
    fn rejects_empty_input() {
        let error = parse_schema_version("").unwrap_err();

        assert!(matches!(error, PreambleError::MissingSchemaHeader));
    }

    #[test]
    fn rejects_invalid_schema_version() {
        let error = parse_schema_version("# RACK:Vlol\nterminal = \"Ghostty\"").unwrap_err();

        assert!(matches!(error, PreambleError::InvalidSchemaVersion(_)));
    }

    #[test]
    fn rejects_unsupported_schema_version() {
        let error = parse_schema_version("# RACK:V99\nterminal = \"Ghostty\"").unwrap_err();

        assert!(matches!(error, PreambleError::UnsupportedSchemaVersion(99)));
    }

    #[test]
    fn accepts_generated_preamble_before_schema_header() {
        let preamble = format_generated_preamble(Path::new("/tmp/config.toml"), 1);

        assert_eq!(parse_schema_version(&preamble).unwrap(), 1);
    }

    #[test]
    fn formats_generated_preamble() {
        let preamble = format_generated_preamble(Path::new("/tmp/config.toml"), 1);

        assert_eq!(
            preamble,
            "# RACK:GENERATED\n# Source config is /tmp/config.toml\n# Do not edit this file directly.\n\n# RACK:V1"
        );
    }

    #[test]
    fn rejects_arbitrary_comments_before_schema_header() {
        let error = parse_schema_version("# hello\n# RACK:V1").unwrap_err();

        assert!(matches!(error, PreambleError::MissingSchemaHeader));
    }
}
